services:
  - type: web
    name: litlens-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0